### ISSUE TITLE
Enable/disable cron per environment

### ISSUE THREAD

**Issue by pingers** [universityofadelaide/shepherd#79]
As a site administrator 
I want to be able to enable/disable cron 
so that I can ensure it only runs as needed and not during down time.

https://docs.openshift.com/container-platform/3.6/dev_guide/cron_jobs.html
This doesn't actually show the suspend flag, but it's
```
spec:
  suspend: true/false
```

**Comment by pingers** [comment]
This could be a dropdown option for each environment at /site/{site-id}/environments which toggles between
Enable cron/Disable cron

Thoughts?

**Comment by singularo** [comment]
Before we can do that bit, we need the ability to do the suspending, which is implemented in these PR's
https://github.com/universityofadelaide/shepherd/pull/83
https://github.com/universityofadelaide/openshift-client/pull/21

**Comment by singularo** [comment]
This is implemented
